apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    name: prometheus
  annotations:
    prometheus.io/scrape: 'true'
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - targetPort: 9090
    port: 443
  selector:
    app: prometheus
