apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    dns.alpha.kubernetes.io/external: "nginx.dev.infra.meltwater.io"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:849122192484:certificate/dd2c372c-f158-4998-8b73-2fc71382ded7"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 80
  selector:
    app: nginx
